# Generated by Django 4.1.4 on 2022-12-27 17:27

from django.db import migrations, models
import django.db.models.deletion
import django_mysql.models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Tree",
            fields=[
                ("id", models.PositiveIntegerField(primary_key=True, serialize=False)),
                (
                    "title",
                    django_mysql.models.SizedTextField(size_class=4, verbose_name=1),
                ),
                (
                    "image",
                    django_mysql.models.SizedTextField(size_class=4, verbose_name=1),
                ),
                ("color", models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "username",
                    models.CharField(max_length=20, primary_key=True, serialize=False),
                ),
                ("password", models.CharField(max_length=45)),
                ("first_name", models.CharField(max_length=45)),
                ("last_name", models.CharField(max_length=45)),
                ("email", models.EmailField(max_length=254)),
                ("date_of_birth", models.DateTimeField()),
                (
                    "gender",
                    django_mysql.models.EnumField(
                        choices=[
                            ("male", "Male"),
                            ("female", "Female"),
                            ("other", "Other"),
                        ]
                    ),
                ),
                ("country", models.CharField(max_length=45)),
                ("city", models.CharField(max_length=45)),
                (
                    "profile_image",
                    django_mysql.models.SizedTextField(size_class=4, verbose_name=1),
                ),
                ("sees_tree", models.ManyToManyField(to="web_app.tree")),
            ],
        ),
        migrations.AddField(
            model_name="tree",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="web_app.user"
            ),
        ),
        migrations.CreateModel(
            name="Note",
            fields=[
                ("id", models.PositiveIntegerField(primary_key=True, serialize=False)),
                (
                    "title",
                    django_mysql.models.SizedTextField(size_class=4, verbose_name=1),
                ),
                ("time_created", models.DateTimeField(auto_now_add=True)),
                ("time_modified", models.DateTimeField(auto_now=True)),
                ("time_viewed", models.DateTimeField()),
                ("locked", models.BooleanField(default=True)),
                ("hidden", models.BooleanField(default=True)),
                (
                    "image",
                    django_mysql.models.SizedTextField(size_class=4, verbose_name=1),
                ),
                ("color", models.PositiveIntegerField()),
                (
                    "markdown_text",
                    django_mysql.models.SizedTextField(size_class=4, verbose_name=3),
                ),
                (
                    "parent_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="web_app.note"
                    ),
                ),
                (
                    "references",
                    models.ManyToManyField(
                        related_name="referenced_by", to="web_app.note"
                    ),
                ),
                (
                    "tree_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="web_app.tree"
                    ),
                ),
            ],
        ),
    ]
